# App Service Sample Configuration
# This YAML file configures an App Service deployment

# Project metadata
metadata:
  projectName: sampleproject
  environment: dev
  location: eastus

# Resource tags
tags:
  environment: development
  project: bicep-infrastructure
  owner: infrastructure-team

# Feature toggles
featureToggles:
  appService: true

# Module configurations
moduleConfigurations:
  appService:
    name: sampleapp
    sku: B1
    runtimeStack: DOTNETCORE|6.0
    systemAssignedIdentity: true
    userAssignedIdentities: {}
    
    # App settings
    appSettings:
      - name: WEBSITE_RUN_FROM_PACKAGE
        value: "1"
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
      - name: AzureWebJobsStorage
        value: DefaultEndpointsProtocol=https;AccountName=storageaccount;AccountKey=key;EndpointSuffix=core.windows.net
    
    # Connection strings
    connectionStrings:
      - name: DefaultConnection
        value: Server=myserver.database.windows.net;Database=mydb;User Id=admin;Password=password;
        type: SQLAzure
    
    # Diagnostics configuration
    diagnostics:
      enabled: true
      logAnalyticsWorkspaceId: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/logs-rg/providers/Microsoft.OperationalInsights/workspaces/app-logs
      logCategories:
        - AppServiceHTTPLogs
        - AppServiceConsoleLogs
        - AppServiceAppLogs
      retentionDays: 30
    
    # Deployment slots
    deploymentSlots:
      - name: staging
        appSettings:
          - name: ASPNETCORE_ENVIRONMENT
            value: Staging
        autoSwapSlotName: production
    
    # Sticky settings (preserved during slot swaps)
    stickySettings:
      appSettingNames:
        - WEBSITE_RUN_FROM_PACKAGE
      connectionStringNames:
        - DefaultConnection
