# .NET Aspire Sample Configuration
# This YAML file demonstrates configuring .NET Aspire resources

# Project metadata
metadata:
  projectName: aspire-demo
  environment: dev
  location: eastus

# Resource tags
tags:
  environment: development
  project: aspire-microservices
  owner: development-team
  costCenter: "54321"

# Feature toggles
featureToggles:
  enableAspire: true
  enableKeyVault: true
  enableStorageAccount: true
  enableSqlDatabase: true

# .NET Aspire configuration
aspire:
  containerApps:
    environment:
      name: aspire-env
      logAnalyticsWorkspaceName: aspire-logs
      zoneRedundant: false
    services:
      - name: catalog-api
        source:
          type: container
          image: ghcr.io/myorg/catalog-api:latest
        resources:
          cpu: "0.5"
          memory: "1Gi"
        scale:
          minReplicas: 1
          maxReplicas: 5
          rules:
            - name: http-rule
              type: http
              metadata:
                concurrentRequests: "100"
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ConnectionStrings__CatalogDb
            secretRef: catalog-connection-string
        ingress:
          external: true
          targetPort: 80
          transport: http
          
      - name: basket-api
        source:
          type: container
          image: ghcr.io/myorg/basket-api:latest
        resources:
          cpu: "0.5"
          memory: "1Gi"
        scale:
          minReplicas: 1
          maxReplicas: 3
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: Redis__ConnectionString
            secretRef: redis-connection-string
        dependencies:
          - redis-cache
        ingress:
          external: false
          targetPort: 80
          
      - name: identity-service
        source:
          type: code
          codeRepository: https://github.com/myorg/identity-service
          codeBranch: main
        resources:
          cpu: "1.0"
          memory: "2Gi"
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: JWT__SecretKey
            secretRef: jwt-secret-key
        ingress:
          external: true
          targetPort: 80
          
      - name: redis-cache
        source:
          type: container
          image: redis:alpine
        resources:
          cpu: "0.25"
          memory: "512Mi"
        scale:
          minReplicas: 1
          maxReplicas: 1
          
  registry:
    name: aspirecr
    sku: Standard
    
  monitoring:
    applicationInsights:
      name: aspire-insights
      samplingPercentage: 100

# Module configurations
moduleConfigurations:
  keyVault:
    name: aspire-kv
    sku: standard
    enablePurgeProtection: false
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
    enableRbacAuthorization: true
    secrets:
      - name: catalog-connection-string
        value: "Server=aspire-sql.database.windows.net;Database=CatalogDb;User Id=admin;Password=P@ssw0rd;"
      - name: redis-connection-string
        value: "redis-cache:6379,password=redispassword"
      - name: jwt-secret-key
        value: "VerySecureJwtSigningKey123!@#"
        
  sqlDatabase:
    serverName: aspire-sql
    databaseName: CatalogDb
    administratorLogin: admin
    administratorLoginPassword: P@ssw0rd
    sku:
      name: Basic
      tier: Basic
      capacity: 5
    maxSizeBytes: 2147483648
    zoneRedundant: false
    enableAuditing: true
    enableThreatDetection: true
    enableTransparentDataEncryption: true
    firewallRules:
      - name: AllowAllAzureServices
        startIpAddress: 0.0.0.0
        endIpAddress: 0.0.0.0
